default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=120]
      exclude: ^dist/|^third_party/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^dist/|^third_party/

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--line-length=120]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
    -   id: absolufy-imports

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.0.1
  #   hooks:
  #     - id: trailing-whitespace
  #       exclude: ^tests/.*/fixtures/.*|cosmos1/models/diffusion/nemo/post_training/multicamera/.*
  #       args: [--markdown-linebreak-ext=md]
  #     - id: end-of-file-fixer
  #       exclude: ^tests/.*/fixtures/.*|cosmos1/models/diffusion/nemo/post_training/multicamera/.*
  #     - id: check-added-large-files
  #       args: ['--maxkb=2000']