name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed  # This triggers even if Lint fails

jobs:
  check-video-links:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Video Link Checker
        run: python scripts/check_video_links.py